In [21]:
import numpy as np
import pandas as pd
import random
import warnings
import time
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, RandomizedSearchCV, KFold
from sklearn import preprocessing

In [25]:
# our initial dataset

data = pd.read_csv('data_cleaned.csv')
#data = data.dropna(how='any',axis=0) # drop every missing rows
X = data.iloc[:,1:]; y = data.iloc[:,0]
data.head()

,team_one_win,duration,team_one_barons,team_two_barons,team_one_dragons,team_two_dragons,team_one_rift_heralds,team_two_rift_heralds,team_one_first_baron,team_one_first_blood,...,"team_two_mid_champ_(139.0, 144.0]","team_two_mid_champ_(144.0, 148.0]","team_two_mid_champ_(148.0, 149.0]","team_two_bot_champ_(-0.001, 98.0]","team_two_bot_champ_(98.0, 109.0]","team_two_bot_champ_(109.0, 117.0]","team_two_bot_champ_(117.0, 123.0]","team_two_bot_champ_(123.0, 128.0]","team_two_bot_champ_(128.0, 132.0]","team_two_bot_champ_(132.0, 133.0]"
0,0,0.758468,0,2,2,4,0,0,0,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0.531370,0,1,4,1,2,0,0,1,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,0.387923,0,0,3,0,2,0,0,1,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,0.303682,0,0,2,0,0,0,0,1,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0,0.476289,0,1,1,3,1,1,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [29]:
warnings.simplefilter('ignore')
clf1 = KNeighborsClassifier(n_neighbors=1)
for clf, label in zip([clf1], ['KNN']):
    start_time = time.time()
    scores = cross_val_score(clf, X, y, cv=5, scoring='accuracy')
    print("Accuracy: %0.4f (+/- %0.4f) [%s] [time execution: %0.4f]" 
          % (scores.mean(), scores.std(), label, time.time() - start_time))

Accuracy: 0.8147 (+/- 0.0073) [KNN] [time execution: 5.7008]

In [27]:
cross_val_score(clf1, X, y, cv=5, scoring='accuracy')

array([0.76116346, 0.75860656, 0.75122951, 0.74098361, 0.75860656])